### ISSUE TITLE
Add tool to automate library versioning tasks

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#10]
Making releases, merging bug-fixes into supported branches, etc.

Using https://github.com/sociomantic-tsunami/octod/.

**Comment by gavin-norman-sociomantic** [comment]
The fundamentals of what this tool should do are described in the [library maintainers doc](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-maintainer.rst).

**Comment by gavin-norman-sociomantic** [comment]
**Updating versioning info in the README**

Each project's README should have a section listing the currently maintained major versions and when they are maintained until. [ocean's README](https://github.com/sociomantic-tsunami/ocean#maintained-major-branches), for example.

The tool could automatically update the README when making major releases. (Bearing in mind that it will need to be updated in all maintained major branches, not just in the branch being released.)

**Comment by gavin-norman-sociomantic** [comment]
**Clearing release notes**

The `relnotes` folder (e.g. [ocean's](https://github.com/sociomantic-tsunami/ocean/tree/v2.x.x/relnotes)) should be cleared when releasing. The tool could do this automatically.

**Comment by leandro-lucarella-sociomantic** [comment]
@mathias-baumann-sociomantic maybe you want to self-assign when you accept the invitation :)

**Comment by mathias-baumann-sociomantic** [comment]
Propose interface:

```
 # prepare a release, that is, create a milestone, optionally add the given issues to it
neptune prepare v1.2.0 --issues 34,63,77
[neptune] Creating milestone v1.2.1
[neptune] Adding issues [34,63,77] to the milestone
[neptune] done.

# Do a release
neptune release v1.2.0
[neptune] Detected a minor release v1.1.4 -> v1.2.0
[neptune] Building release notes
[neptune] Creating & pushing tag 'v1.2.0'
[neptune] Creating Github Release
[neptune] Closing milestone 'v1.2.0'
[neptune] Clearing release notes
[neptune] Create minor branch 'v1.2.x'? (Y/N): Y
[neptune] Creating & pushing minor branch 'v1.2.x'
[neptune] Merge changes in to subsequent branches [v2.x.x', 'v3.x.x']? (Y/N) Y
[neptune] Merging into branches ['v2.x.x', 'v3.x.x']
[neptune]    => Merging into v2.x.x
[neptune]    Detected merge conflict. Please fix the conflicts and type `neptune continue`
[...]
neptune continue
[neptune] Continuing merging of v2.x.x ... done
[neptune]    => Merging into v3.x.x ... done
[neptune] Release v2.1.0 with changes from v1.2.0? (Y/N) N
[neptune] Release v3.3.0 with changes from v1.2.0? (Y/N) N

# Merge changes from various branches into subsequent ones
neptune merge
[neptune] Merge changes from 'v1.2.x' into ['v2.2.x', 'v3.1.3', 'v4.6.2']? (Y/N) Y
[...]
[neptune] Merge changes from 'v2.2.x' into ['v3.1.3', 'v4.6.2']? (Y/N) Y
[...]
```

**Comment by mihails-strasuns-sociomantic** [comment]
Don't have any comments about `prepare` - usually thi part is trivial to do by hand but don't mind having it either.

`release` is the big deal here, some ideas about it:

- One important thing to keep in mind is that amount of maintained minor branches varies per repo right now - we could either standardize the amount (I guess with automatic tool having more maintained versions would be less painful) or put that information into `.neptune.yml` for the tool to read.

- I think it would be better to print a full planned operation summary first (with whole merge train sequence) to confirm and execute them one by one later. That would also naturally enable a "dry run" mode.

- Asking to open release note preview in `$EDITOR` to fixup/approve would be nice

- The tool has to be very smart already anyway, why not deduce planned release tag based on current branch name when typing just `neptune release`? :)

- Future feature: when doing minor releases, add new entry to https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/LibFeatures.d

- Future feature: when doing major releases, update table in readme (https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/README.rst#maintained-major-branches)

**Comment by mihails-strasuns-sociomantic** [comment]
I would also suggest naming `merge` command `merge-upwards` instead or something like that (it has reverse direction from plain git merge command)

**Comment by mathias-lang-sociomantic** [comment]
```
neptune prepare v1.2.0 --issues 34,63,77
[neptune] Creating milestone v1.2.1
```

I assume that's a typo and you meant v1.2.0 in the second line ?

**Comment by mathias-baumann-sociomantic** [comment]
Yes, it was a typo

**Comment by mathias-lang-sociomantic** [comment]
```
[neptune] Create minor branch 'v1.2.x'? (Y/N): Y
[neptune] Creating & pushing minor branch 'v1.2.x'
[neptune] Merge changes in to subsequent branches [v2.x.x', 'v3.x.x']? (Y/N) Y
```

Could also ask if one wants to delete the oldest feature branch, if it exists.
As in: `[neptune] Delete branch v1.0.x? (y/N)`

Last thing, from your example it seems there is a `v1.2.0` => `v2.x.x` merge, and a `v1.2.0` => `v3.x.x` merge, right ? If so shouldn't v2.x.x be merged into v3.x.x (assuming merge resolution from v2 will help for the merge in v3).

**Comment by gavin-norman-sociomantic** [comment]
Sounds good! I agree with all points mentioned above.

**Comment by leandro-lucarella-sociomantic** [comment]
I would make the tool require the less user input as possible. I know at first is risky to just to everything without asking, but my experience with other tools is, when you finally trust the tool, being so interactive is just an annoyance. I think for scary commands one can have a `--dry-run` and/or a `--interactive` flag (another option would be to be more conservative and make it interactive by default and introduce a `--assume-yes` that just answer everything with yes).

This includes deleting the oldest branch. I would make the information about what branches are maintained part of `.neptune.yml` so we can automate as much as possible.

**Comment by mathias-baumann-sociomantic** [comment]
I could do that yeah. What about having an artifical delay between steps of like 2 seconds so the user could ctrl+c if they felt they need to?

**Comment by nemanja-boric-sociomantic** [comment]
Maybe it could also be helpful if the `neptune release` would do all the branching/merging business locally, so afterwards user could open `gitk` and inspect what's has been done, followed by `neptune release push` or `neptune release --abort`.

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic with my suggestion to print all planned operations upfront it shouldn't be an issue - you only need to confirm action once after examining all printed commands in one batch. Nice trait of this tool is that all "write" operations are done locally can thus any run effectively starts as "dry run", you only need to confirm final sync to remote repo. Pretty much what @nemanja-boric-sociomantic has said.

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, that makes sense. I like @nemanja-boric-sociomantic 's suggestion.

**Comment by leandro-lucarella-sociomantic** [comment]
:tada:
