### ISSUE TITLE
neptune-release asks "Please enter the upstream remote name" multiple times

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#116]
I'm not sure why it even asks this once, but it certainly seems excessive to ask it multiple times during the release process.

**Comment by joseph-wakeling-sociomantic** [comment]
As a related note: `[neptune]` config contains both `upstream` and `upstream-remote` values.  Why the need for both?  Wouldn't the latter cover all eventualities?

**Comment by mathias-baumann-sociomantic** [comment]
`upstream` is the github user / repo. `upstream-remote` is the the local remote name. We need to fetch
the latest state from github because we do local operations, but we also need the github name/repo to identify it when we do calls via the github API

**Comment by joseph-wakeling-sociomantic** [comment]
Doesn't knowledge of the (locally-defined) `upstream-remote` inherently tell you what the actual GitHub repo is?

**Comment by mathias-baumann-sociomantic** [comment]
Yes, we also parse it out of that value. But there have been occasions where one wants to use a different remote than specified in there, thus both it's configurable. It's also stored so we don't re-parse it every time.
