### ISSUE TITLE
Pre-release tags must use dotted notation

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/neptune#132]
https://semver.org says:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

Right now neptune uses `rc1` form, which is incorrect and must be changed to `rc.1` instead.

**Comment by leandro-lucarella-sociomantic** [comment]
Just for more clarity, if this is not done, `rc10` will be interpreted as an older version than `rc2` (same for alphas and betas).

**Comment by leandro-lucarella-sociomantic** [comment]
Also, we should make sure the semver parser is taking this into account (tokenize the pre-release using the dots as separators and sorting purely numeric components numerically instead of lexically).
