### ISSUE TITLE
neptune-release cannot properly handle first releases (for v0.x.x?)

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/neptune#134]
The use-case: preparing the first release of a new library.  The default branch is `v0.x.x`.

When trying to prepare a first release using `neptune-release` (which I would expect to be tagged as `v0.1.0`), I get the following output:

```
We are on branch v0.x.x
Warning: No previous releases found. This should only be the case for your very first release!
Detected release <invalid>
Warning: No corresponding milestone found for <invalid>
Actions to be done:
 * Creating annotated tag <invalid> (git tag -F- <invalid> v0.x.x)
 * Create tracking branch v0.0.x (git branch v0.0.x <invalid>)
 * Create next major branch v1.x.x (git branch v1.x.x)
 * Checkout next major branch v1.x.x (git checkout v1.x.x)
 * Removing release notes (...)
 * Commiting removal of release notes (git commit -m Clear release notes after release)
 * Checkout original branch v0.x.x (git checkout v0.x.x)

Would you like to continue? y/n: n
```

If `neptune-release` is invoked with the `--pre-release` flag, things fare a little better but the inferred tag is clearly problematic:

```
We are on branch v0.x.x
Warning: No previous releases found. This should only be the case for your very first release!
Detected release v0.0.0-rc1
Warning: No corresponding milestone found for v0.0.0-rc1
Actions to be done:
 * Creating annotated tag v0.0.0-rc1 (git tag -F- v0.0.0-rc1 v0.x.x)
 * Checkout original branch v0.x.x (git checkout v0.x.x)
```

It's not clear (since I've never had cause to use it in other circumstances) whether there is a general problem of support for first releases, or whether it's support for a `v0.x.x` first release specifically that is missing (probably because it has not been attempted until now).

**Comment by mathias-baumann-sociomantic** [comment]
I am pretty sure this is because of `v0.x.x` as opposed to `v1.x.x` as first release.

Though, I don't share your expectation that the version number would be `v0.1.0`. You're doing a major release after all, not a minor, so I'd expect `v0.0.0` ;)

When I wrote it, I didn't even think that someone would use v0 as first version, so those cases are rather unhandled at the moment

**Comment by joseph-wakeling-sociomantic** [comment]
> Though, I don't share your expectation that the version number would be v0.1.0. You're doing a major release after all, not a minor, so I'd expect v0.0.0 ;)

I'm not sure that's the general convention for first 0.x.x release, although it's interesting that AFAICS the semver spec isn't precise about how v0.x.y releases should be numbered.

Some projects even have 0.0.x initial releases, but that reasonably seems not in line with semver spec on the meaning of the MAJOR, MINOR and PATCH fields, so I think we can ignore that use-case.

My own take is that v0.0.0 is reasonably interpreted as "no code", so the very first release of actual functionality is quite reasonably v0.1.0.

**Comment by mathias-lang-sociomantic** [comment]
Well, reading https://semver.org/ :

> How should I deal with revisions in the 0.y.z initial development phase?
>
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

First item under FAQ.

**Comment by mathias-baumann-sociomantic** [comment]
Hmm and ignoring patch releases altogether?

**Comment by joseph-wakeling-sociomantic** [comment]
> First item under FAQ.

D'oh!  I don't know how I missed that.  I suppose I could claim that FAQ is not spec ;-)

**Comment by joseph-wakeling-sociomantic** [comment]
> Hmm and ignoring patch releases altogether?

I'm not sure I follow what you mean here.  But it seems reasonable that the first release cannot be a patch release, because it's inherently introducing new features (and not just bugfixes).

**Comment by mathias-baumann-sociomantic** [comment]
Sure, but I mean any further release. The FAQ says to only increment minor then.

**Comment by joseph-wakeling-sociomantic** [comment]
I would imagine that could proceed in normal fashion.  I mean, if you're doing a follow-up release on the `v0.x.x` branch it would be a new minor release (this already works), and if you're doing a follow up release on (say) the v0.1.x branch, it'll be a patch release (this also already works).

**Comment by mathias-baumann-sociomantic** [comment]
That seems to be the easiest solution

**Comment by mihails-strasuns-sociomantic** [comment]
It does make some sense that if you are in full unstable mode, there is not much to gain from separating bug fixes into own releases. Though judging by what I see in various package registries, people still do point releases.

**Comment by mihails-strasuns-sociomantic** [comment]
(I would suggest doing whatever is easiest to implement as this is shady topic ;))

**Comment by joseph-wakeling-sociomantic** [comment]
@mihails-strasuns-sociomantic yes, but ultimately this is a maintainer's policy choice, and a maintainer can reasonably choose to have a v0.x.y policy that says any increment to the minor version may be breaking, but allow backwards-compatible patch releases, for example.

Bottom line is this is _entirely_ about creating a first release from a v0.x.x branch.  Everything else works fine (as shown by e.g. dmxnet where we have used `neptune-release` to release both patch releases and new minor releases in the v0.x.x series).
