### ISSUE TITLE
Release notes headings missing

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#142]
The new release notes format ([described here](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-contributor.rst)) includes a heading for each individual note. `neptune-release` doesn't appear to handle these correctly: they're not present in the final release notes.

Example:
[This PR](https://github.com/sociomantic-tsunami/swarm/pull/206) included [these release notes](https://github.com/gavin-norman-sociomantic/swarm/blob/69dfce4a636388ac181337206762420498992232/relnotes/ctors.deprecation.md) (note the heading **Strip down client core constructors to those used with config and in tests**). The [final release notes](https://github.com/sociomantic-tsunami/swarm/releases/tag/v4.5.0) don't include the heading at all.

**Comment by mihails-strasuns-sociomantic** [comment]
Note: they are included in mail release notes, but not in GitHub release.

**Comment by gavin-norman-sociomantic** [comment]
I didn't get the email output to the console either, unfortunately :(

(#143)

**Comment by mathias-baumann-sociomantic** [comment]
The problem seems to be that your new header style is interpreted as comment by the git client when creating the annotated tag message. And the tag message later is used to build the github releases. However, the email is using a different source and thus still has the headers.
