### ISSUE TITLE
Release email test not output to console

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#143]
Previously, if the email config was not set up properly, the release email was output to the console. I'm not sure if this is a bug or was deliberately removed, but I used to find it useful.

**Comment by mathias-baumann-sociomantic** [comment]
The email is always printed. The only case where it isn't is when you **didn't** properly setup the email recipients. In that case you should see

> Can't send email, neptune.mail-recipient config missing or corrupt!

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, and this is exactly what @gavin-norman-sociomantic complains about (and me too). I don't want to setup email as I will never be sending it automatically. But it was convenient to have mail text printed to easily copy-paste and edit.
