### ISSUE TITLE
Releases made with `--pre-release` are not marked as pre-releases

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#148]
e.g. https://github.com/sociomantic-tsunami/swarm/releases/tag/v5.0.0-rc.2 and https://github.com/sociomantic-tsunami/swarm/releases/tag/v5.0.0-rc.1.

Compare with https://github.com/sociomantic-tsunami/swarm/releases/tag/v5.0.0-rc.1%2Bd2, for example, which is marked as a pre-release.

**Comment by leandro-lucarella-sociomantic** [comment]
I just bumped to this one. I guess it should be a super easy fix.
