### ISSUE TITLE
Links in neptune update issues wrong

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#152]
For example https://github.com/sociomantic-tsunami/dhtnode/pull/66, contains links to https://github.com/sociomantic-tsunami/makd/releases/tag/v4.6.0 and https://github.com/sociomantic-tsunami/makd/compare/v4.5.1...v4.6.0. (`makd` instead of `swarm`.)

**Comment by gavin-norman-sociomantic** [comment]
(The inclusion of these links is really nice, though!)

**Comment by mathias-baumann-sociomantic** [comment]
Mind you, you created an issue for a bug discovered while testing a not even PR'ed feature ;)
I am closing this for now but I fixed the problem in my uncommitted code already.

**Comment by gavin-norman-sociomantic** [comment]
>Mind you, you created an issue for a bug discovered while testing a not even PR'ed feature ;)

Is there a better place to make a note of such things?

**Comment by mathias-baumann-sociomantic** [comment]
I am not sure to be honest.. I suppose you did the right thing.. and I fixed it and closed it?

**Comment by mathias-baumann-sociomantic** [comment]
just without any associated PR or committ..

**Comment by gavin-norman-sociomantic** [comment]
Yep, cool. I just wondered because of your complaining tone:
>Mind you, you created an issue for a bug discovered while testing a not even PR'ed feature ;)
