### ISSUE TITLE
no support for default ~master branch ?

### ISSUE THREAD

**Issue by stefan-koch-sociomantic** [sociomantic-tsunami/neptune#154]
I am currently working on releasing dfmt.
and I get the following assertion.
object.Exception@./src/release/versionHelper.d(71): Invalid branch name! Expected 'v..'!
debugging showed that the name chosen was "master"
which is the default branch of the repository.

**Comment by stefan-koch-sociomantic** [comment]
The problems seems to be that neptune expects _all_ branches in the repo the obey the `vx.x.x` scheme.

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/neptune/issues/147
