### ISSUE TITLE
Suggestion for commit title/message for auto update tool

### ISSUE THREAD

**Issue by ben-palmer-sociomantic** [sociomantic-tsunami/neptune#159]
The commit title and message could perhaps be a bit more verbose. For the commit title (shamelessly stolen from @daniel-zullo-sociomantic):
`Advance [submodule name] from v[x.x.x] to v[x.x.x] `

and for the commit message it would be good to include the "default" git subsum output of the last five commits.

**Comment by mathias-baumann-sociomantic** [comment]
Adjusting the title is easy, however adding the subsum output is very expensive and was not considered important enough for inclusion.

I am thinking I could even allow teams to define their own commit title message using .neptune.yml.

What do you think @gavin-norman-sociomantic ?

**Comment by gavin-norman-sociomantic** [comment]
I don't think it should be configurable. It should be easy enough to come up with something that satisfies the majority of people.

**Comment by mathias-baumann-sociomantic** [comment]
I used the suggested format now. Will close this issue accordingly. Feel free to reopen if you feel the need
