### ISSUE TITLE
autopr: have a dedicated testing pr (?)

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/neptune#166]
summarized the idea is, have one "Testing" PR that is meant to stay open to which all updates are always pushed and from which users can unsubscribe.

Normal PRs can and should still be created

@mathias-lang-sociomantic fyi

**Comment by leandro-lucarella-sociomantic** [comment]
Can you put a more meaningful title to this issue?

**Comment by mathias-baumann-sociomantic** [comment]
We kind of have this already. The description of it should maybe be updated though.
