### ISSUE TITLE
Wrong version detected when two tags point to the same sha

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/neptune#172]
Resulting in a broken update PR

**Comment by mathias-lang-sociomantic** [comment]
Could that also affect the overview tool ? I'm seeing a generated overview which shows applications dependending on MakD `v2.2.0-rc.1` even though `v2.2.0` is released and point to the same commit.

**Comment by mihails-strasuns** [comment]
Very likely
