### ISSUE TITLE
AutoPR: Include release/commits link directly in commit text

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/neptune#183]
fyi @joseph-wakeling-sociomantic

**Comment by mathias-lang-sociomantic** [comment]
In general, it would be nice if you could describe more what is wanted / why. I was looking through issue (to see if the one I wanted to create already existed) but with the level of description in those issues, I cannot be sure it does. Not to mention, if someone wanted to take over some of those issues, [s]he'll have a hard time figuring out the requirements.
