### ISSUE TITLE
[autopr] Ignore repositories without default branch

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/neptune#199]
Neptune currently fails with an exception if it finds the repository without a default branch. Instead, the
repository should just be ignored.

**Comment by mathias-baumann-sociomantic** [comment]
Is that the current problem why it isn't running?

**Comment by mathias-baumann-sociomantic** [comment]
I am pretty sure this is not the problem. The exception is not from what you said. It's merely logging a problem but not stopping because of that.
