### ISSUE TITLE
Mark when a dependency is not pointing to a tag

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/neptune#26]
We have a situation where some apps do not depend on a tagged release, but instead of a specific commit.
While this may not be a situation we want, Neptune currently simply doesn't output anything, so it looks like the application / library doesn't depend on the project.

**Comment by gavin-norman-sociomantic** [comment]
Perhaps this should be displayed as a :radioactive: symbol.
