### ISSUE TITLE
Broken links between maintainer and user rst docs

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic-tsunami/neptune#33]
The links between the docs [Using Neptune-Versioned Libraries <library-user.rst>](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-user.rst) and [Maintaining Neptune-Versioned Libraries <library-maintainer.rst>](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-maintainer.rst)
are referring to a non-existing file. 

> ...Maintainers of Neptune-versioned libraries should also read
`Maintaining Neptune Libraries <neptune-maintainer.rst>`_.

> You should first read `Using Neptune-Versioned Libraries <neptune-user.rst>`_ to
get a grounding in the principles and theory of Neptune from the point-of-view
of a user of a library.

Should the files be renamed or the link changed?

**Comment by leandro-lucarella-sociomantic** [comment]
No PR? :blush:

**Comment by andreas-bok-sociomantic** [comment]
> Should the files be renamed or the link changed?

Will, once this is settled :)
