### ISSUE TITLE
Patch release does not push major branch after merge

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#65]
Making the [v4.1.4 release of swarm](https://github.com/sociomantic-tsunami/swarm/releases/tag/v4.1.4), I encountered the following situation:
```
Actions to be done:
 * Creating annotated tag v4.1.4 (git tag -F- v4.1.4 v4.1.x)
 * Checkout v4.x.x locally (git checkout v4.x.x)
 * Merge v4.1.4 into v4.x.x (git merge -m "Merge tag v4.1.4 into v4.x.x" v4.1.4)
 * Checkout original branch v4.1.x (git checkout v4.1.x)
```
This is correct and was correctly carried out on my local repo.

However, on replying `y` to the prompt `Would you like to push the modified references now?`, the commit merging v4.1.4 into v4.x.x was not pushed upstream. (I presume it's supposed to.)

**Comment by mathias-baumann-sociomantic** [comment]
Did the prompt list the reference as modified?

**Comment by gavin-norman-sociomantic** [comment]
I don't remember. I guess I should have pasted more of the output :/

**Comment by mathias-baumann-sociomantic** [comment]
Yes. Yes you should have.

**Comment by mathias-baumann-sociomantic** [comment]
And which version of the tool were you using?

**Comment by gavin-norman-sociomantic** [comment]
5e503a34465a96605fd9ef70905658a19b22f60e

**Comment by nemanja-boric-sociomantic** [comment]
I have experienced the same situation, but I prescribed this to the my local clone being broken: https://github.com/sociomantic-tsunami/neptune/issues/64 It could be I was wrong.

**Comment by mathias-baumann-sociomantic** [comment]
no it was a genuine bug but it's already in a PR
