### ISSUE TITLE
Release: Add option to not do a full merge train

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#66]
Sometimes, it's useful to get all the nice automagical features of the release tool, but just for a single release, with no merge train.

An example of this situation is when you're making a patch release which is to be merged into a subsequent minor branch but which cannot be released there immediately, as other fixes still need to be added (possibly fixes which rely on the merged patch release, even).

**Comment by mathias-baumann-sociomantic** [comment]
For clarification: Do you want to do only a release INCLUDING merges, or literaly ONLY a release?

**Comment by gavin-norman-sociomantic** [comment]
Just a release. As we add more features to the release tool (collating release notes, making the github release, sending email, etc), it's useful to just be able to do that with the tool, separately from the whole merge train, when necessary.

Unless this would complicate things enormously.

**Comment by mathias-baumann-sociomantic** [comment]
No that should be fine

**Comment by mathias-baumann-sociomantic** [comment]
This has been implemented in https://github.com/sociomantic-tsunami/neptune/pull/43/commits/10cdcc6f66f5c6828b075c62bf589604fe8989e9
