### ISSUE TITLE
There should be a way to configure the upstream remote instead of guessing

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#87]
The current heuristics to get what the upstream git remote name is is quite weak, as said in #76. Ideally there should be a way for the user to just set it as a neptune-release configuration via `git config` or something.

Probably `git config hub.upstream` could be used as a way to guess too in the process, and after guessing this should be saved in the config for future use.

**Comment by mathias-baumann-sociomantic** [comment]
`hub.upstream` has no information what so ever about the remote name?

**Comment by leandro-lucarella-sociomantic** [comment]
> hub.upstream has no information what so ever about the remote name?

Nope, sorry, it was an error. In the upcoming git-hub v1.0.0 there will be a `upstreamremote`, you could check for that for future-compatibility, but for now the upstream repo is sort of hardcoded in git-hub.
