### ISSUE TITLE
Minor release: check if the `LibFeatures.d` has been updated

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/neptune#89]
Before performing minor release we need to check if the `LibFeatures.d` (if exists) is updated with the newest `has_features_x_y` constant:

https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/LibFeatures.d#L20

**Comment by mathias-lang-sociomantic** [comment]
Dup of https://github.com/sociomantic-tsunami/neptune/issues/48
