### ISSUE TITLE
Using git config merge.ff = only breaks neptune

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#90]
I have `git config merge.ff only` configured globaly, to avoid unexpected merges when normally in my workflow all merges should be FF. When I do want to make a merge that is actually creating a merge commit, I just use `--no-ff`.

Since neptune handle merges without any specific ff options, I get an error when the merge can't be done simply FF (most of cases in neptune, this is exactly the only cases where I do want non-ff merges).

I think it might be better to use `--no-ff` in neptune directly. The only problem is a merge commit will be created even if it could be a ff merge, but I think it is good information to have when a branch was really merge in another, right?

FYI @gavin-norman-sociomantic and @mihails-strasuns-sociomantic too.

**Comment by mihails-strasuns-sociomantic** [comment]
> I think it might be better to use --no-ff in neptune directly.

Yes, this is not only desired but actually a must - I always supply it when doing manual releases.

**Comment by mathias-lang-sociomantic** [comment]
Honestly for branch forwarding, I prefer to have ff when possible. Can't `neptune` just use `--ff` ?

**Comment by mihails-strasuns-sociomantic** [comment]
There is no branch forwarding with neptune releases, ever. Sometimes ff is possible but it is just a coincidence - if you allow it, git graph information about release relation will much harder to follow.

**Comment by mathias-lang-sociomantic** [comment]
> if you allow it, git graph information about release relation will much harder to follow.

How so ? You'll still see the tag. And it provides additional information (that they are identical).

**Comment by mihails-strasuns-sociomantic** [comment]
Tags are much harder to rely on in this context. Right now I can use `git log --merges --pretty=oneline` to quickly check if any branch has already merged earlier release. It is both very simple and very reliable - and as soon as fast forwards are allowed, to get same info one needs to write script to traverse history and search for tags.

There is no benefit in knowing that some release branches don't diverge - it is just a distracting coincidence.

**Comment by leandro-lucarella-sociomantic** [comment]
I agree that this is one of those rare cases where you really want a merge commit, no matter what.
