### ISSUE TITLE
When neptune is interrupted is not clear if I should run the last command manually

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#91]
I got a merge problem:
```
Merge v0.2.1 into v0.x.x ...
	git merge -m "Merge tag v0.2.1 into v0.x.x" v0.2.1
fatal: Not possible to fast-forward, aborting.

Exit the shell when you are done.(CTRL+D or 'exit')
```
I really wasn't sure if I should only fix the problem at hand and then just resume (a la `git rebase` + fix + `git add` + `git rebase --continue`) or if I should run the last command myself before resuming (like `git rebase` + fix + `git commit` + `git rebase --continue`).

I decided to do the merge myself and it seems to have worked, but I still don't know what would happen if I didn't. It might be good to give the user more information on what are the expectations when that shell is given.

**Comment by mathias-baumann-sociomantic** [comment]
Did you mean to end both of your alternatives with `git rebase --continue`? Because they look pretty much identical to me..

**Comment by leandro-lucarella-sociomantic** [comment]
Well, they are not, one makes the commit for you before continuing. The point was, is not clear if after fixing the problem I should:

* just `git add` the files?
* also `commit` them?
* do a `merge --continue` afterwards?

I think the command should state how the user should resume the processing, how far is the user expected to go in the resolution process.

**Comment by mathias-baumann-sociomantic** [comment]
As far as I know `git rebase` it doesn't matter if you do a commit or not, it auto-commits in that case anyway...

**Comment by leandro-lucarella-sociomantic** [comment]
yeah, only if you `git add`ed stuff, otherwise it will complain.
