### ISSUE TITLE
Support pre-releases

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#94]
At some point pre-releases should be supported.

As a first step, if creating pre-releases is too complicated, at least it could be smart enough to ignore them when creating new releases.

I have the situation now in makd where I created a v2.0.0-rc1 manually, and now I want to release the v2.0.0 with neptune, but it wants to created v2.1.0 instead.

**Comment by mathias-baumann-sociomantic** [comment]
When doing a pre-release, do you usually do the releases based on the pre-release as well?

**Comment by mathias-baumann-sociomantic** [comment]
for prereleases, will you want to specify "rcX" yourself or should neptune just always use that string and increment the number on its own? I would opt for the later option

**Comment by leandro-lucarella-sociomantic** [comment]
I think the most convenient way would be to have a `--rc` option that will just look for the latest `-rcX` tag in the current branch and increment `X` (or start with `1` if there is none). Eventually it will be nice to have an option to completely override what the tool guesses (just in case).
